export const INITIAL_STATE = {
  '0,0': 'default',
  '0,1': 'default',
  '0,2': 'default',
  '0,3': 'default',
  '0,4': 'default',
  '0,5': 'default',
  '1,0': 'default',
  '1,1': 'red',
  '1,2': 'default',
  '1,3': 'default',
  '1,4': 'default',
  '1,5': 'default',
  '2,0': 'default',
  '2,1': 'default',
  '2,2': 'default',
  '2,3': 'default',
  '2,4': 'default',
  '2,5': 'default',
  '3,0': 'default',
  '3,1': 'default',
  '3,2': 'default',
  '3,3': 'default',
  '3,4': 'default',
  '3,5': 'default',
  '4,0': 'default',
  '4,1': 'default',
  '4,2': 'default',
  '4,3': 'default',
  '4,4': 'green',
  '4,5': 'default',
  '5,0': 'default',
  '5,1': 'default',
  '5,2': 'default',
  '5,3': 'default',
  '5,4': 'default',
  '5,5': 'default',
};

export const COLORS = {
  default: 'mediumslateblue',
  red: 'red',
  green: 'green',
};
