export const INITIAL_STATE = {
  '0,0': 'default',
  '0,1': 'default',
  '0,2': 'default',
  '0,3': 'default',
  '0,4': 'default',
  '0,5': 'default',
  '1,0': 'default',
  '1,1': 'default',
  '1,2': 'default',
  '1,3': 'default',
  '1,4': 'default',
  '1,5': 'default',
  '2,0': 'default',
  '2,1': 'default',
  '2,2': 'Fima',
  '2,3': 'Kris',
  '2,4': 'default',
  '2,5': 'default',
  '3,0': 'default',
  '3,1': 'default',
  '3,2': 'Anya',
  '3,3': 'Tema',
  '3,4': 'default',
  '3,5': 'default',
  '4,0': 'default',
  '4,1': 'default',
  '4,2': 'default',
  '4,3': 'default',
  '4,4': 'default',
  '4,5': 'default',
  '5,0': 'default',
  '5,1': 'default',
  '5,2': 'default',
  '5,3': 'default',
  '5,4': 'default',
  '5,5': 'default',
};

export const COLORS = {
  Fima: 'rgba(255, 215, 0, 0.55)',
  Kris: 'rgba(57, 255, 20, 0.55)',
  Tema: 'rgba(0, 123, 255, 0.55)',
  Anya: 'rgba(255, 0, 255, 0.55)',
  default: '#003366',
};

export const PLAYERS = ['Fima', 'Tema', 'Anya', 'Kris'];

export const THEME_URIS = {
  potatoes: Object.keys(import.meta.glob('/src/assets/themes/potatoes/*.*')),
  birthday: Object.keys(import.meta.glob('/src/assets/themes/birthday/*.*')),
  cheese: Object.keys(import.meta.glob('/src/assets/themes/cheese/*.*')),
  sport: Object.keys(import.meta.glob('/src/assets/themes/sport/*.*')),
  transport: Object.keys(import.meta.glob('/src/assets/themes/transport/*.*')),
  duets: Object.keys(import.meta.glob('/src/assets/themes/duets/*.*')),
  gadgets: Object.keys(import.meta.glob('/src/assets/themes/gadgets/*.*')),
  deserts: Object.keys(import.meta.glob('/src/assets/themes/deserts/*.*')),
  toys: Object.keys(import.meta.glob('/src/assets/themes/toys/*.*')),
  movies: Object.keys(import.meta.glob('/src/assets/themes/movies/*.*')),
  myths: Object.keys(import.meta.glob('/src/assets/themes/myths/*.*')),
  furniture: Object.keys(import.meta.glob('/src/assets/themes/furniture/*.*')),
  medicine: Object.keys(import.meta.glob('/src/assets/themes/medicine/*.*')),
  instruments: Object.keys(import.meta.glob('/src/assets/themes/instruments/*.*')),
  drinks: Object.keys(import.meta.glob('/src/assets/themes/drinks/*.*')),
  vegetables: Object.keys(import.meta.glob('/src/assets/themes/vegetables/*.*')),
  architecture: Object.keys(import.meta.glob('/src/assets/themes/architecture/*.*')),
  dogs: Object.keys(import.meta.glob('/src/assets/themes/dogs/*.*')),
  dishes: Object.keys(import.meta.glob('/src/assets/themes/dishes/*.*')),
  flags: Object.keys(import.meta.glob('/src/assets/themes/flags/*.*')),
  backpack: Object.keys(import.meta.glob('/src/assets/themes/backpack/*.*')),
  jobs: Object.keys(import.meta.glob('/src/assets/themes/jobs/*.*')),
  birds: Object.keys(import.meta.glob('/src/assets/themes/birds/*.*')),
  bath: Object.keys(import.meta.glob('/src/assets/themes/bath/*.*')),
  plants: Object.keys(import.meta.glob('/src/assets/themes/plants/*.*')),
  holidays: Object.keys(import.meta.glob('/src/assets/themes/holidays/*.*')),
  breakfast: Object.keys(import.meta.glob('/src/assets/themes/breakfast/*.*')),
  singers: Object.keys(import.meta.glob('/src/assets/themes/singers/*.*')),
  capitals: Object.keys(import.meta.glob('/src/assets/themes/capitals/*.*')),
  animals: Object.keys(import.meta.glob('/src/assets/themes/animals/*.*')),
  series: Object.keys(import.meta.glob('/src/assets/themes/series/*.*')),
  beach: Object.keys(import.meta.glob('/src/assets/themes/beach/*.*')),
  fridge: Object.keys(import.meta.glob('/src/assets/themes/fridge/*.*')),
  body: Object.keys(import.meta.glob('/src/assets/themes/body/*.*')),
  fruits: Object.keys(import.meta.glob('/src/assets/themes/fruits/*.*')),
  anya: Object.keys(import.meta.glob('/src/assets/themes/anya/*.*')),
};

export const THEMES = {
  potatoes: true,
  birthday: true,
  cheese: true,
  sport: true,
  transport: false,
  duets: false,
  gadgets: false,
  deserts: false,
  toys: false,
  movies: false,
  myths: false,
  furniture: false,
  medicine: false,
  instruments: false,
  drinks: false,
  vegetables: false,
  architecture: false,
  dogs: false,
  dishes: false,
  flags: false,
  backpack: false,
  jobs: false,
  birds: false,
  bath: false,
  plants: false,
  holidays: false,
  breakfast: false,
  singers: false,
  capitals: false,
  animals: false,
  series: false,
  beach: false,
  fridge: false,
  body: false,
  fruits: false,
  anya: false,
};

export const THEME_NAMES = {
  potatoes: 'Страви з картоплі',
  birthday: 'Атрибути до ДН',
  cheese: 'Види сирів',
  sport: 'Види спорту',
  transport: 'Види транспорту',
  duets: 'Відомі дуети',
  gadgets: 'Гаджети',
  deserts: 'Десерти',
  toys: 'Іграшки',
  movies: 'Кадр з фільму',
  myths: 'Казкові та міфічні персонажі',
  furniture: 'Меблі',
  medicine: 'Медицина',
  instruments: 'Музичні інструменти',
  drinks: 'Напої',
  vegetables: 'Овочі',
  architecture: 'Памʼятки архітектури',
  dogs: 'Породи собак',
  dishes: 'Посуд',
  flags: 'Прапори',
  backpack: 'Предмети у шкільному рюкзаку',
  jobs: 'Професії',
  birds: 'Птахи',
  bath: 'Речі, які є у ванній',
  plants: 'Рослини',
  holidays: 'Свята',
  breakfast: 'Сніданки',
  singers: 'Співаки та співачки',
  capitals: 'Столиці',
  animals: 'Тварини',
  series: 'Телесеріали',
  beach: 'У пляжній сумці',
  fridge: 'У холодильнику',
  body: 'Частини тіла',
  fruits: 'Ягоди та фрукти',
  anya: 'Що подобається Ані',
};
